version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:3000"  # changed external port from 3000 to 3001
    container_name: wanderlust_frontend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    container_name: wanderlust_backend
    restart: unless-stopped
