version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:3000"  # Host:Container - Access frontend via http://localhost:3001
    container_name: wanderlust_frontend
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"  # Host:Container - Access backend via http://localhost:5000
    container_name: wanderlust_backend
    restart: unless-stopped
